# Generated by Django 4.2.11 on 2024-04-16 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('username', models.CharField(default='None', max_length=25)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=128)),
                ('hostname', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Find',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_find', models.DateTimeField(default=django.utils.timezone.now)),
                ('lieu', models.CharField(max_length=100)),
                ('departement', models.CharField(max_length=100)),
                ('commune', models.CharField(max_length=100)),
                ('arrondissement', models.CharField(max_length=100)),
                ('quartier', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=100)),
                ('is_valid', models.BooleanField(default=False)),
                ('is_dropped', models.BooleanField(default=False)),
                ('info_categorie', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(default='Carrefour Calvaire, Fidjrossè', max_length=100)),
                ('tel', models.CharField(default='+229 52 52 52 31', max_length=100)),
                ('email', models.EmailField(default='contact@it-servicegroup.com', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Lose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_declaration', models.DateTimeField(default=django.utils.timezone.now)),
                ('lieu', models.CharField(max_length=100)),
                ('departement', models.CharField(max_length=100)),
                ('commune', models.CharField(max_length=100)),
                ('arrondissement', models.CharField(max_length=100)),
                ('quartier', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=100)),
                ('is_published', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_losed', models.BooleanField(default=False)),
                ('is_stealed', models.BooleanField(default=False)),
                ('is_client_valid', models.BooleanField(default=False)),
                ('is_retrieve', models.BooleanField(default=False)),
                ('info_categorie', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Retrieve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_retrieve', models.DateTimeField(default=django.utils.timezone.now)),
                ('info_temoins', models.TextField()),
                ('photo', models.ImageField(upload_to='media/find/photo')),
                ('document', models.FileField(upload_to='media/find/document')),
                ('find', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.find')),
                ('info_categorie', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.categorie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TypeCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TypeNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TypeAbonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('valeur', models.IntegerField()),
                ('is_valid', models.BooleanField(default=False)),
                ('when', models.DateTimeField(default=django.utils.timezone.now)),
                ('type_notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.typenotification')),
                ('who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Temoignage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_temoignage', models.DateTimeField(default=django.utils.timezone.now)),
                ('temoignage', models.TextField()),
                ('object_retrieve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.retrieve')),
            ],
        ),
        migrations.CreateModel(
            name='Souscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_valid', models.BooleanField(default=False)),
                ('is_canceled', models.BooleanField(default=False)),
                ('date_canceled', models.DateTimeField(blank=True, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('type_abonnement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.typeabonnement')),
            ],
        ),
        migrations.CreateModel(
            name='Publish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_published', models.DateTimeField(default=django.utils.timezone.now)),
                ('lose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.lose')),
                ('retrieve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.retrieve')),
            ],
        ),
        migrations.AddField(
            model_name='lose',
            name='souscription',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.souscription'),
        ),
        migrations.AddField(
            model_name='lose',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='find',
            name='souscription',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.souscription'),
        ),
        migrations.AddField(
            model_name='find',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='categorie',
            name='type_categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.typecategorie'),
        ),
    ]
