# Generated by Django 4.2.11 on 2024-04-29 13:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Find',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_find', models.DateTimeField(default=django.utils.timezone.now)),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('prenom', models.CharField(blank=True, max_length=100, null=True)),
                ('tel', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('lieu', models.CharField(blank=True, max_length=100, null=True)),
                ('departement', models.CharField(blank=True, max_length=100, null=True)),
                ('commune', models.CharField(blank=True, max_length=100, null=True)),
                ('arrondissement', models.CharField(blank=True, max_length=100, null=True)),
                ('quartier', models.CharField(blank=True, max_length=100, null=True)),
                ('adresse', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, default='Description détaillée', null=True)),
                ('is_valid', models.BooleanField(default=False)),
                ('is_dropped', models.BooleanField(default=False)),
                ('is_subscribe', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('is_retrieve', models.BooleanField(default=False)),
                ('info_categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse', models.CharField(default='Carrefour Calvaire, Fidjrossè', max_length=100)),
                ('tel', models.CharField(default='+229 52 52 52 31', max_length=100)),
                ('email', models.EmailField(default='contact@it-servicegroup.com', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Lose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_declaration', models.DateTimeField(default=django.utils.timezone.now)),
                ('lieu', models.CharField(blank=True, max_length=100, null=True)),
                ('departement', models.CharField(blank=True, max_length=100, null=True)),
                ('commune', models.CharField(blank=True, max_length=100, null=True)),
                ('arrondissement', models.CharField(blank=True, max_length=100, null=True)),
                ('quartier', models.CharField(blank=True, max_length=100, null=True)),
                ('adresse', models.CharField(blank=True, max_length=100, null=True)),
                ('object_value', models.DecimalField(decimal_places=3, default=0.0, max_digits=9)),
                ('reward_value', models.IntegerField(blank=True, default=False, null=True)),
                ('is_reward', models.BooleanField(default=False)),
                ('is_dropped', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_losed', models.BooleanField(default=False)),
                ('is_stealed', models.BooleanField(default=False)),
                ('is_client_valid', models.BooleanField(default=False)),
                ('is_retrieve', models.BooleanField(default=False)),
                ('info_categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Parametre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pourcentage', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5)),
                ('valeur_reel', models.PositiveIntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Temoignage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_temoignage', models.DateTimeField(default=django.utils.timezone.now)),
                ('temoignage', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TypeNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TypeAbonnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('valeur', models.DecimalField(decimal_places=3, max_digits=9)),
                ('nombre_de_jours', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('type_notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.typenotification')),
            ],
        ),
        migrations.CreateModel(
            name='Souscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('is_valid', models.BooleanField(blank=True, default=False)),
                ('is_canceled', models.BooleanField(blank=True, default=False)),
                ('date_canceled', models.DateTimeField(blank=True, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('type_abonnement', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.typeabonnement')),
            ],
        ),
        migrations.CreateModel(
            name='Retrieve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_retrieve', models.DateTimeField(default=django.utils.timezone.now)),
                ('info_temoins', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='media/find/photo')),
                ('document', models.FileField(blank=True, null=True, upload_to='media/find/document')),
                ('find', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.find')),
                ('info_categorie', models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='app.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Publish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_published', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_publish', models.BooleanField(default=False)),
                ('lose', models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='app.lose')),
                ('retrieve', models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='app.retrieve')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('publish', models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='app.publish')),
                ('souscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.souscription')),
            ],
        ),
        migrations.AddField(
            model_name='categorie',
            name='type_categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.typecategorie'),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email_or_phone', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('hostname', models.CharField(blank=True, max_length=255, null=True)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login_date', models.DateTimeField(blank=True, null=True)),
                ('last_modify_date', models.DateTimeField(blank=True, null=True)),
                ('deactivate_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
    ]
