# Generated by Django 4.2.11 on 2024-05-03 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='find',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='find',
            name='arrondissement',
        ),
        migrations.RemoveField(
            model_name='find',
            name='commune',
        ),
        migrations.RemoveField(
            model_name='find',
            name='departement',
        ),
        migrations.RemoveField(
            model_name='find',
            name='description',
        ),
        migrations.RemoveField(
            model_name='find',
            name='quartier',
        ),
        migrations.RemoveField(
            model_name='lose',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='lose',
            name='arrondissement',
        ),
        migrations.RemoveField(
            model_name='lose',
            name='commune',
        ),
        migrations.RemoveField(
            model_name='lose',
            name='departement',
        ),
        migrations.RemoveField(
            model_name='lose',
            name='quartier',
        ),
        migrations.RemoveField(
            model_name='retrieve',
            name='info_categorie',
        ),
        migrations.AddField(
            model_name='notification',
            name='retrieve',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.retrieve'),
        ),
        migrations.AddField(
            model_name='souscription',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='publish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.publish'),
        ),
        migrations.AlterField(
            model_name='publish',
            name='lose',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.lose'),
        ),
        migrations.AlterField(
            model_name='publish',
            name='retrieve',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.retrieve'),
        ),
        migrations.AlterField(
            model_name='souscription',
            name='type_abonnement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.typeabonnement'),
        ),
    ]
