# Generated by Django 4.2.11 on 2024-05-17 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_payment_delete_parametre_remove_publish_lose_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='find',
            old_name='info_categorie',
            new_name='categorie',
        ),
        migrations.RenameField(
            model_name='lose',
            old_name='info_categorie',
            new_name='categorie',
        ),
        migrations.RemoveField(
            model_name='find',
            name='couleur',
        ),
        migrations.RemoveField(
            model_name='find',
            name='immatricul',
        ),
        migrations.RemoveField(
            model_name='find',
            name='marque',
        ),
        migrations.RemoveField(
            model_name='find',
            name='ram',
        ),
        migrations.RemoveField(
            model_name='find',
            name='rom',
        ),
        migrations.AddField(
            model_name='lose',
            name='age',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lose',
            name='couleur',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lose',
            name='gender',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lose',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/lose/photo'),
        ),
        migrations.AddField(
            model_name='lose',
            name='immatricul',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lose',
            name='language_speak',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lose',
            name='marque',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lose',
            name='ram',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lose',
            name='rom',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lose',
            name='skin_color',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lose',
            name='tail',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='lose',
            name='type_categorie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.typecategorie'),
        ),
    ]
