# Generated by Django 4.2 on 2023-11-27 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='article.item')),
                ('species', models.CharField(max_length=255)),
                ('owner_name', models.CharField(max_length=255)),
                ('owner_phone', models.CharField(max_length=20)),
                ('owner_email', models.EmailField(max_length=254)),
                ('last_seen_location', models.CharField(max_length=255)),
                ('date_and_time_of_loss', models.DateTimeField()),
                ('additional_details', models.TextField(blank=True)),
                ('is_find', models.BooleanField(default=False)),
                ('found_location', models.CharField(blank=True, max_length=255, null=True)),
            ],
            bases=('article.item',),
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='article.item')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=100)),
                ('plate_number', models.CharField(max_length=20)),
                ('vin', models.CharField(max_length=17)),
                ('last_seen_location', models.CharField(max_length=255)),
                ('date_and_time_of_loss', models.DateTimeField()),
                ('owner_name', models.CharField(max_length=255)),
                ('owner_phone', models.CharField(max_length=20)),
                ('owner_email', models.EmailField(max_length=254)),
                ('documents', models.FileField(blank=True, upload_to='car_documents/')),
                ('interior_description', models.TextField(blank=True)),
                ('has_gps', models.BooleanField(default=False)),
                ('is_find', models.BooleanField(default=False)),
                ('found_location', models.CharField(blank=True, max_length=255, null=True)),
            ],
            bases=('article.item',),
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='article.item')),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('last_seen_location', models.CharField(max_length=255)),
                ('date_and_time_of_loss', models.DateTimeField()),
                ('additional_details', models.TextField(blank=True)),
                ('is_find', models.BooleanField(default=False)),
                ('found_location', models.CharField(blank=True, max_length=255, null=True)),
            ],
            bases=('article.item',),
        ),
        migrations.CreateModel(
            name='Key',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='article.item')),
                ('description', models.CharField(max_length=255)),
                ('owner_name', models.CharField(max_length=255)),
                ('owner_phone', models.CharField(max_length=20)),
                ('owner_email', models.EmailField(max_length=254)),
                ('last_seen_location', models.CharField(max_length=255)),
                ('date_and_time_of_loss', models.DateTimeField()),
                ('additional_details', models.TextField(blank=True)),
                ('is_find', models.BooleanField(default=False)),
                ('found_location', models.CharField(blank=True, max_length=255, null=True)),
            ],
            bases=('article.item',),
        ),
        migrations.CreateModel(
            name='MobilePhone',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='article.item')),
                ('make', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('owner_name', models.CharField(max_length=255)),
                ('owner_phone', models.CharField(max_length=20)),
                ('owner_email', models.EmailField(max_length=254)),
                ('last_seen_location', models.CharField(max_length=255)),
                ('date_and_time_of_loss', models.DateTimeField()),
                ('additional_details', models.TextField(blank=True)),
                ('is_find', models.BooleanField(default=False)),
                ('found_location', models.CharField(blank=True, max_length=255, null=True)),
            ],
            bases=('article.item',),
        ),
        migrations.CreateModel(
            name='Motorcycle',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='article.item')),
                ('make', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('year', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=255)),
                ('plate_number', models.CharField(max_length=20)),
                ('vin', models.CharField(max_length=17)),
                ('last_seen_location', models.CharField(max_length=255)),
                ('date_and_time_of_loss', models.DateTimeField()),
                ('owner_name', models.CharField(max_length=255)),
                ('owner_phone', models.CharField(max_length=20)),
                ('owner_email', models.EmailField(max_length=254)),
                ('documents', models.FileField(blank=True, upload_to='motorcycle_documents/')),
                ('additional_details', models.TextField(blank=True)),
                ('is_find', models.BooleanField(default=False)),
                ('found_location', models.CharField(blank=True, max_length=255, null=True)),
            ],
            bases=('article.item',),
        ),
        migrations.CreateModel(
            name='USBKey',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='article.item')),
                ('description', models.CharField(max_length=255)),
                ('last_seen_location', models.CharField(max_length=255)),
                ('date_and_time_of_loss', models.DateTimeField()),
                ('additional_details', models.TextField(blank=True)),
                ('is_find', models.BooleanField(default=False)),
                ('found_location', models.CharField(blank=True, max_length=255, null=True)),
            ],
            bases=('article.item',),
        ),
    ]
