# Generated by Django 4.2 on 2023-11-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='additional_details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='documents',
            field=models.FileField(blank=True, upload_to='car_documents/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='interior_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='individual',
            name='additional_details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='key',
            name='additional_details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mobilephone',
            name='additional_details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='additional_details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='motorcycle',
            name='documents',
            field=models.FileField(blank=True, upload_to='motorcycle_documents/'),
        ),
        migrations.AlterField(
            model_name='usbkey',
            name='additional_details',
            field=models.TextField(blank=True),
        ),
    ]
