# Generated by Django 4.2 on 2023-11-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_delete_find_delete_nofind'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='is_find',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='animal',
            name='share_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='is_find',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='share_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='individual',
            name='is_find',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='individual',
            name='share_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='key',
            name='is_find',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='key',
            name='share_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='is_find',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mobilephone',
            name='share_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='is_find',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='motorcycle',
            name='share_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usbkey',
            name='is_find',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usbkey',
            name='share_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
