# Generated by Django 4.2 on 2023-11-24 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_animal_is_find_animal_share_location_car_is_find_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='share_location',
        ),
        migrations.RemoveField(
            model_name='car',
            name='share_location',
        ),
        migrations.RemoveField(
            model_name='individual',
            name='share_location',
        ),
        migrations.RemoveField(
            model_name='key',
            name='share_location',
        ),
        migrations.RemoveField(
            model_name='mobilephone',
            name='share_location',
        ),
        migrations.RemoveField(
            model_name='motorcycle',
            name='share_location',
        ),
        migrations.RemoveField(
            model_name='usbkey',
            name='share_location',
        ),
    ]
